[package]
name = "rather"
version = "0.1.0"
authors = ["saethlin <kimockb@gmail.com>"]

[lib]
name = "rather"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rand = "*"
GSL = "*"
rust-ini = "*"
itertools = "*"
quadrature = "*"
rulinalg = "*"
numpy = "*"
ndarray = "0.9.1"

[dependencies.cpython]
version = "*"
features = ["extension-module"]
