[package]
name = "rather"
version = "0.1.0"
authors = ["saethlin <kimockb@gmail.com>"]

[dependencies]
rand = "*"
GSL = "*"
rust-ini = "*"
itertools = "*"
quadrature = "*"
rulinalg = "*"
numpy = "*"
ndarray = "0.9.1"
bencher = "*"
png = "*"
rustfft = "*"
num-complex = "*"
gnuplot = "*"
rayon = "*"

[dependencies.cpython]
version = "*"
features = ["extension-module"]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
