[package]
name = "lather"
version = "0.0.0"
authors = ["Benjamin Kimock <kimockb@gmail.com>"]
license = "MIT/Apache-2.0"
build = "build.rs"

description = "A Rust crate and Python extension for modeling starspot effects on radial velocity and photometric observations, inspired by complaints about the SOAP project of similar goals."
repository = "https://github.com/saethlin/rust-lather"
documentation = "https://docs.rs/lather/"

keywords = ["astronomy"]
categories = ["science", "simulation"]

[features]
simd = ["faster"]

[dependencies]
rand = "0.4"
itertools = "0.7"
quadrature = "0.1"
rulinalg = "0.4"
ndarray = "0.11"
bencher = "0.1.5"
png = "0.11"
rustfft = "2.0"
num-complex = "0.1"
gnuplot = "0.0"
rayon = "1.0"
derivative = "1.0"
faster = {git="https://github.com/AdamNiederer/faster", optional=true}
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"

[dependencies.GSL]
version = "0.4"
features = ["v2"]

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
cbindgen = "0.5.2"

[profile.release]
lto = true

